default: &default
  adapter: mysql2
  encoding: utf8mb4

development:
  <<: *default
  database:  connectus_development

test:
  <<: *default
  database:  connectus_test

production:
  <<: *default
  database:  connectus_test