development:
  DB_HOSTNAME: localhost
  DB_NAME: connectus_development
  DB_NAME_TEST: connectus_test
  DB_USERNAME: root
  DB_PASSWORD: ""
  USER_DOC: admin
  PASS_DOC: qwerty
  SEND_EMAIL: true
  EMAIL_FROM: "d693d2031ccfbd"
  EMAIL_PASSWORD: "2548f7117473b8"
  EMAIL_TO: "paulotijero@etiner.com"
  EMAIL_PROVIDER: smtp.mailtrap.io
  EMAIL_PORT: "2525"
  EMAIL_DOMAIN: smtp.mailtrap.io
  EMAIL_AUTHENTICATION: cram_md5
  BASE_APP: http://localhost:3000
  ID_UNIQUE_API: 03989d7119834c1ab53af5769895e37e
  SECRET_API: 2ec17bcd5fbf455ebffc9255f4a86e40
  DST_PHONE: "56990449006"
production:
  DB_HOSTNAME: localhost
  DB_NAME: connectus_test
  DB_NAME_TEST: connectus_test
  DB_USERNAME: root
  DB_PASSWORD: ""
  EMAIL_FROM: "no-reply@etiner.com"
  SEND_EMAIL: false
  EMAIL_PASSWORD: "etiner20.17"
  EMAIL_TO: "paulotijero@etiner.com"
  EMAIL_PROVIDER: smtp.gmail.com
  EMAIL_PORT: "587"
  EMAIL_DOMAIN: localhost
  EMAIL_AUTHENTICATION: cram_md5
  BASE_APP: http://localhost:3000
  ID_UNIQUE_API: 03989d7119834c1ab53af5769895e37e
  SECRET_API: 2ec17bcd5fbf455ebffc9255f4a86e40
  DST_PHONE: "56990449006"